import { b as createComponent, r as renderTemplate, m as maybeRenderHead, u as unescapeHTML } from './astro_Qw7etMx4.mjs';
import 'kleur/colors';
import 'clsx';

const html = "<p>A script in Processing to dynamically create cat faces based on hand drawn components.</p>";

				const frontmatter = {"name":"DynamiCat","status":3,"cover":{"src":"~/assets/images/projects/DynamiCat/threeCats.png","alt":"Three cat faces generated by the DynamiCat script"},"tags":["processing","svg"],"github":"https://github.com/rewfergu/dynamiCat","readingTime":1};
				const file = "/Users/robertferguson/Projects/rewferguson/src/content/words/dynamicat.md";
				const url = undefined;
				function rawContent() {
					return "\nA script in Processing to dynamically create cat faces based on hand drawn components.\n";
				}
				function compiledContent() {
					return html;
				}
				function getHeadings() {
					return [];
				}

				const Content = createComponent((result, _props, slots) => {
					const { layout, ...content } = frontmatter;
					content.file = file;
					content.url = url;

					return renderTemplate`${maybeRenderHead()}${unescapeHTML(html)}`;
				});

export { Content, compiledContent, Content as default, file, frontmatter, getHeadings, rawContent, url };
