const id = "dynamicat.md";
						const collection = "words";
						const slug = "dynamicat";
						const body = "\nA script in Processing to dynamically create cat faces based on hand drawn components.\n";
						const data = {name:"DynamiCat",cover:{src:"~/assets/images/projects/DynamiCat/threeCats.png",alt:"Three cat faces generated by the DynamiCat script"},tags:["processing","svg"]};
						const _internal = {
							type: 'content',
							filePath: "/Users/robertferguson/Projects/rewferguson/src/content/words/dynamicat.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
